// Code generated by "stringer -type=Event"; DO NOT EDIT.

package rutina

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventRoutineStart-0]
	_ = x[EventRoutineStop-1]
	_ = x[EventRoutineComplete-2]
	_ = x[EventRoutineFail-3]
	_ = x[EventAppStop-4]
	_ = x[EventAppComplete-5]
	_ = x[EventAppFail-6]
}

const _Event_name = "EventRoutineStartEventRoutineStopEventRoutineCompleteEventRoutineFailEventAppStopEventAppCompleteEventAppFail"

var _Event_index = [...]uint8{0, 17, 33, 53, 69, 81, 97, 109}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
